# Project information
site_name: RA Seguros
site_author: Ciro Bermudez
site_description: Descripcion del sitio web

# Copyright
copyright: >-
  Copyright &copy; 2025 RA Seguros

# Configuration
theme:
  name: material
  custom_dir: assets
  language: es
  palette:

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  features:
    - navigation.indexes
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.expand
    - navigation.sections
    - header.autohide
    - content.code.copy
  font:
    text: Inter
    code: Monaco
  favicon: assets/images/site_logo/favicon.svg
  logo: assets/images/site_logo/logo.svg

# Plugins
plugins:
  - search

# Additional configuration
extra:
  generator: false
  social:
  - icon: simple/facebook
    link: https://www.facebook.com/sebastianrulli
  - icon: simple/instagram
    link: https://www.instagram.com/sebastianrulli/
  - icon: simple/tiktok
    link: https://www.tiktok.com/@sebastianrullitiktok
  - icon: simple/whatsapp
    link: https://api.whatsapp.com/send?phone=2224897969&text=Hola!%20Me%20gustar%C3%ADa%20recibir%20m%C3%A1s%20informaci%C3%B3n.
#  - icon: fontawesome/brands/gitlab
#    link: https://baltig.infn.it/vip/vrf_docs

# Custom stylesheets
extra_css:
  - stylesheets/extra.css

# Custom javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Inicio:
    - index.md
  - Servicios:
    - services/index.md
    - Opciones de seguro:
      - services/seguros/seguro-de-vida.md
      - services/seguros/seguro-medico.md
      - services/seguros/seguro-empresas.md
      - services/seguros/seguro-auto.md
    - Servios financieros:
      - services/finanzas/planes-retiro.md
      - services/finanzas/planes-ahorro.md
  - Contacto:
    - contacts/index.md
